name: Generate README

on:
  push:
    branches:
      - main  

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        haskell-version: 'latest'

    - name: Install dependencies
      run: |
        stack setup
        stack install

    - name: Run README generator script
      run: stack runhaskell generate-readme.hs

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Auto-generate README.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
